### ISSUE TITLE
[Question] 4.3 Definition Augmentation

### ISSUE THREAD

**Issue by agombert** [CLUEbenchmark/DataCLUE#4]
Hey folks, 

Thank you very much for the article, it is really interesting !

I just have a question regarding the **4.3 Definition Augmentation (metadata)**:

> We can use this label definition to create more data. We can assign label definition as a sentence for the dataset if it lacks label definition.

Could you provide some concrete example of it ? I don't understand how you proceeded. 

Thanks !

Arnault

**Comment by brightmart** [comment]
Hi Arnault,
Thanks for your feedback. 

It has two meanings:
1) We can use this label definition to create more data ---> for example, if a label definition is: "Buyers consult what courier to send", then we can generate several sentences  using Definition Augmentation, such as: "What kind of express do you usually send?", "do you send express using DELL?". and these kinds of sentences can be added to the training set. Of course, the label of these inputs is "Buyers consult what courier to send".

2) We can assign label definition as a sentence for the dataset if it lacks label definition.----> if the label is not a sentence, for example, an integer(or number), we can assign meaning sentence for the integer(or number) as label definition, then use Definition Augmentation to generate some data just as step 1).

Liang Xu

**Comment by agombert** [comment]
Hey Liang, 

Thank you very much for your quick answer !

When you say 
>  then we can generate several sentences using Definition Augmentation

You mean that you create manually the example, then use data augmentation ?

Arnault

**Comment by brightmart** [comment]
Yes, it is. We can create it manually at the beginning,  if lack of label definition.
